on:
 push:
  branches:
    - dev

name: 🚀 Deploy website on push (dev)
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp.confitechsol.com
        username: ftpuser@confitechsol.com
        password: EGD_UkJ;q6.d
        server-dir: /hrms/